baseURL = "/"
languageCode = "en-us"
title = "Upshore Immigration Services"
theme = "zafta"
MetaDataFormat = "toml"
Paginate = 5

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 100

[params]
	brand = "Upshore"
	headline = "Achieve Your Canadian Dream"
	adjectives = ["Authorised", "Competent", "Trustworthy"]
	description = "Regulated Canadian Immigration Consultancy"
	description2 = "Authorised. Competent. Trustworthy."
	author = "Shavinder Dandiwal"
